#!/bin/bash

export onbroadwell=True
#export onbroadwell=False

export addname="-intel-2018"

export PETSC_ARCH=linux-intel-64bit
export LOCAL_LIB_DIR=$HOME/software


export PETSC_DIR=${LOCAL_LIB_DIR}/petsc${addname}
#export PETSC_DIR=/p/system/packages/petsc/3.7.5/

# make files readable by group members by default
umask g+rx

export EDITOR="emacs -nw"
alias ed=$EDITOR

alias al='alias'
alias cls='clear'
alias hi='history'
alias la='ls -a'
alias ll='ls -lg'
alias lh='ls -lh'
alias ncv='ncview -minmax all'
alias nch='ncdump -h'
alias em='emacs -nw -Q'
alias myqstat='qstat -u `whoami`'


export PISM_DIR=$HOME/pism18/pism${addname}
export PISM_PREFIX=${PISM_DIR}/bin/
export PISM_DO=echo

# Add private commands to PATH
export PATH=${PISM_PREFIX}:${PISM_DIR}/util/:${LOCAL_LIB_DIR}/bin:$HOME/bin:$PATH

# last initialization step: report settings
/usr/bin/tty -s
if [ 0 = $? ]; then
    module list

    echo 'PETSC_DIR  = ' ${PETSC_DIR}
    echo 'PETSC_ARCH = ' ${PETSC_ARCH}
    echo 'PATH       = ' ${PATH}
fi


module purge

module load cmake/3.10.2
module load intel/2018.1
unset I_MPI_FABRICS

export CC=mpiicc
export CXX=mpiicpc
export FC=mpiifort
export F77=mpiifort

export CFLAGS="-fp-model precise -O3 -xHost -mtune=broadwell"
export CXXFLAGS="-fp-model precise -O3 -xHost -mtune=broadwell"
#export CFLAGS="-axCORE-AVX2 -mtune=broadwell -fp-model precise"
#export CXXLAGS="-axCORE-AVX2 -mtune=broadwell -fp-model precise"
#-no-fast-transcendentals"
#-axCORE-AVX2 
#-xSSE4.2"
#-mkl -ipo -prof-use -prof-dir=/p/tmp/albrecht/sources/build_profiles"


#module load pism/stable1.0

#module load petsc/3.7.5
#module load netcdf-c/4.6.1/intel/parallel

#module load hdf5/1.8.20/intel/parallel
#prepend-path PATH /p/system/packages/hdf5/1.8.20/impi/lib 
#export PATH=$HDF5ROOT/lib/:$PATH

#module load udunits/2.2.26
#module load fftw/3.3.7
#module load gsl/2.4
#module load proj4/5.0.1

module load szip
module load zlib/1.2.11

module load compiler/gnu/7.3.0

module load texlive/2017
module load valgrind/3.10.1/gnu

#not necessary for installation
module load nco/4.6.8 
#module load cdo/1.7.1 
#module load ncview/2.1.6 

# start an interactive job
#alias interact="srun -p debug --nodes=1 --exclusive -I --pty /bin/bash"

export PISM_MPIDO='srun -n'

# don't load anaconda when building PISM: it pulls in its own NetCDF
# stuff, which can confuse things
# module load anaconda/2.3.0
