#!/bin/bash

export CC=gcc
export CXX=g++

module purge
module load PrgEnv-gnu/4.7.3
module load cmake/2.8.12
module load udunits/2.1.24.gnu-4.7.3
# module load netcdf-parallel/4.2.gnu-4.7.3
# module load pnetcdf/1.3.1.gnu-4.7.3
module load gsl
module load fftw/3.3.3.gnu-4.7.3

module load python
module load proj/4.8.0.gnu-4.7.3
module load nco
module load ncview

# load the latest OpenMPI (recent HDF5 uses MPI-2 features not supported by OpenMPI 1.4.x)
module rm openmpi-gnu-4.7.3/1.4.3
module load openmpi/gnu/1.8.8

# start an interactive job
alias interact="qsub -q debug -l nodes=1:ppn=16 -X -I"

export PISM_MPIDO='mpirun -np'
