#!/bin/bash

export PETSC_DIR=~/petsc-maint
export PETSC_ARCH=linux-64bit
export LOCAL_LIB_DIR=$HOME/local

# make files readable by group members by default
umask g+rx

export EDITOR="emacs -nw"
alias ed=$EDITOR

alias al='alias'
alias cls='clear'
alias hi='history'
alias la='ls -a'
alias ll='ls -lg'
alias lh='ls -lh'
alias ncv='ncview -minmax all'
alias nch='ncdump -h'
alias em='emacs -nw -Q'
alias myqstat='qstat -u `whoami`'

export PISM_DIR=~/pism
export PISM_PREFIX=${PISM_DIR}/bin/
export PISM_DO=echo

# Add private commands to PATH
export PATH=${PISM_PREFIX}:${PISM_DIR}/util/:${LOCAL_LIB_DIR}/bin:$HOME/bin:$PATH

# last initialization step: report settings
/usr/bin/tty -s
if [ 0 = $? ]; then
    module list

    echo 'PETSC_DIR  = ' ${PETSC_DIR}
    echo 'PETSC_ARCH = ' ${PETSC_ARCH}
    echo 'PATH       = ' ${PATH}
fi
