#!/bin/bash
# These commands are executed on a login or start of a PBS job.

# First, run the NAS standard setup.

if [ -e /usr/local/lib/init/global.profile ]; then
    . /usr/local/lib/init/global.profile
fi

# Load modules

module purge
module load mpi-intel/2019.5.281
#module load mpi-intel/2020.0.166 # this version does not seem to work
module load comp-intel/2020.4.304
module load pkgsrc/2021Q2
module load python3/3.9.5

export PISM_MPIDO='mpiexec -n'
