name: pism
channels:
  - conda-forge
dependencies:
  - cmake
  - pkg-config
  - openmpi
  - openmpi-mpicc
  - openmpi-mpicxx
  - hdf5
  - netcdf-cxx4
  - gsl
  - swig
  - udunits2
  - nose
  - proj
  - lapack
  - fftw
  - petsc<3.20
  - petsc4py<=3.20
  - xarray
  - h5netcdf
  - matplotlib
  - cartopy
  - pandas
  - geopandas
  - nco
  - cdo
  - nose
  - doxygen
  - notebook
  - ncview
  - tbb=2020.2