name: pism-conda-dbg
channels:
  - conda-forge
  - pism
dependencies:
  - python=3.11.7
  - yaxt
  - yac
  - cmake >=3.16
  - pkg-config
  - make
  - swig
  - gnuconfig   # [unix]
  - hdf5=*=*mpich*
  - h5py=*=*mpich*
  - netcdf-cxx4
  - netcdf4=*=*mpich*
  - fftw
  - gsl >=1.15
  - mpich
  - mpich-mpicc
  - mpich-mpicxx
  - udunits2
  - proj
  - liblzma-devel  # Needed for `pkg-config --exists proj` on at least some python version
  - petsc
  - petsc4py
  - libopenblas
  - xarray
  - matplotlib
  - nco
  - cdo
