name: pism
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - cmake
  - automake
  - autoconf
  - libfyaml
  - libtool
  - m4
  - yaml
  - pkg-config
  - mpich
  - mpich-mpicc
  - mpich-mpicxx
  - mpich-mpifort
  - hdf5=*=*mpich*
  - h5py=*=*mpich*
  - netcdf-cxx4
  - netcdf4=*=*mpich*
  - gsl
  - swig
  - udunits2
  - nose
  - proj
  - lapack
  - fftw
  - petsc<=3.21
  - petsc4py<=3.21
  - xarray
  - h5netcdf
  - matplotlib
  - cartopy
  - pandas
  - geopandas
  - nco
  - cdo
  - nose
  - doxygen
  - notebook
  - ncview
  - tbb=2020.2