#!/bin/bash

# Make sure we stop on errors
set -e 

# Set compiler options
if [[ $1 = "ifx" ]]; then
    COMPILER_OPTS="CC=icx F77=ifx 'FFLAGS=-O3 -march=core-avx2' 'CFLAGS=-O3 -march=core-avx2' 'CLIBS=""' "
elif [[ $1 = "ifort" ]]; then
    COMPILER_OPTS="CC=icc F77=ifort 'FFLAGS=-O3 -march=core-avx2 -mtune=core-avx2 -traceback' 'CFLAGS=-O3 -march=core-avx2 -mtune=core-avx2 -traceback'"
elif [[ $1 = "gfortran" ]]; then
    COMPILER_OPTS=""
else
    echo "Compiler not recognized: $1"
    exit 1
fi

echo "COMPILER_OPTS = $COMPILER_OPTS"
echo ""

### FFTW ###

SRCDIR=$PWD


# with omp enabled
cd $FFTWSRC

autoreconf -fi
eval "./configure --disable-doc --prefix=$SRCDIR/fftw-omp --enable-openmp $COMPILER_OPTS"
make clean
make -j $N
make install

cd $SRCDIR

### LIS ###

SRCDIR=$PWD

# with omp enabled
cd $LISSRC

sed -i.bak '1i\
CLIBS =
' test/Makefile.am

autoreconf -fi
eval "./configure --prefix=$SRCDIR/lis-omp --enable-f90 --enable-omp $COMPILER_OPTS" 
make clean
make -j $N
make install
cd $SRCDIR


echo ""
echo "" 
./check.sh
echo ""
