#!/bin/bash

module load toolchain/pic-intel/2016b
module load devel/CMake/3.5.2-pic-intel-2016b 
module load numlib/FFTW/3.3.5-pic-intel-2016b
module load lib/PROJ/4.9.2-pic-intel-2016b
module load phys/UDUNITS/2.2.20-pic-intel-2016b

# start an interactive job
alias interact="srun -p debug --nodes=1 --exclusive -I --pty /bin/bash"

export PISM_MPIDO='mpirun -np'
