#!/bin/bash

module purge
#module load PrgEnv-intel
module load compiler/icc/2016.3.210-GCC-5.4.0-2.26
module rm cmake/2.8.12
module load cmake/3.5.2
module load cdo/1.7.1
module load gsl/1.16
# load anaconda first because anaconda's ncdump is broken, loading the
# netcdf-parallel later makes sure its ncdump is first in the $PATH
module load python/anaconda2-2.5.0
module load hdf5-parallel/1.8.15p1.intel-2016
# module load parallel-netcdf/-1.6.1.intel-2016
# For some reason parallel-netcdf sets NETCDF_ROOT instead of
# PNETCDF_ROOT, so we have to fix it here.
#export PNETCDF_ROOT=$NETCDF_ROOT
module load netcdf-parallel/4.3.3.1-parallel.intel-2016
module load proj/4.9.2RC2
module load slurm
# the parallel-netcdf module sets the same environment variables as the
# netcdf-parallel module, confusing PISM's build system
# module load parallel-netcdf/1.6.1.intel-2016

# start an interactive job
alias interact="srun -p debug --nodes=1 --exclusive -I --pty /bin/bash"

export PISM_MPIDO='mpirun -np'
