#!/bin/bash

umask 007

module purge
module load slurm
module load intel/2023a
module load imkl-FFTW/2023.1.0
module load netCDF
module load UDUNITS/2.2.28 
module load PROJ/9.2.0
module load CMake/3.26.3
module load GSL/2.7

export LOCAL_LIB_DIR=$HOME/local-rl8
export PISM_DIR=$LOCAL_LIB_DIR/pism
export PISM_PREFIX=${PISM_DIR}/bin/
export PETSC_DIR=$LOCAL_LIB_DIR/petsc
export PETSC_ARCH=opt-64bit

# start an interactive job
alias interact="srun -p debug --nodes=1 --exclusive -I --pty /bin/bash"

# export PYTHONPATH=$PETSC_DIR/$PETSC_ARCH/lib:$PYTHONPATH

export PISM_MPIDO='mpirun -np'
