#!/bin/bash

umask 007

module purge
module load gcc/11.2.0
module load intel-mkl
module load openmpi/4.1.6
module load openblas
module load cmake
module load fftw
module load gsl
module load libxml2
module load curl
module load proj
module load udunits
module load zlib
module load libszip

export LOCAL=$HOME/local-gcc
export BUILD=$LOCAL/build
export PISM_DIR=$LOCAL/pism
export PISM_PREFIX=${PISM_DIR}
export PETSC_DIR=$LOCAL/petsc
export PETSC_ARCH=arch-linux-c-opt

# start an interactive job
alias interact="srun -p debug --nodes=1 --exclusive -I --pty /bin/bash"

export PATH=$PISM_PREFIX/bin:$LOCAL/openmpi/bin:$LOCAL/bin:$LOCAL/hdf5/bin:$LOCAL/netcdf/bin:$PATH
export PYTHONPATH=$PETSC_DIR/$PETSC_ARCH/lib:$PYTHONPATH
#export LD_LIBRARY_PATH=$LOCAL/hdf5/lib:$LOCAL/netcdf/lib:$PATH


export PISM_MPIDO='mpirun -np'
