#!/bin/bash

umask 007

module purge
module load intel/2024.1
module load impi/2021.12
module load intel-rt/2024.1.0
module load cmake/3.20.0
module load fftw/3.3.8
module load anaconda/2024.02-py311 
module load gsl/2.4
module load libxml2
module load curl
module load proj/6.2.0
module load udunits/2.2.28
module load zlib/1.2.11
module load libszip/2.1.1

export LOCAL=$HOME/local-intel
export PISM_DIR=$LOCAL/pism
export BUILD=$LOCAL/build
export PISM_PREFIX=${PISM_DIR}
export PETSC_DIR=$LOCAL/petsc-intel
export PETSC_ARCH=arch-linux-c-opt

# start an interactive job
alias interact="srun -p debug --nodes=1 --exclusive -I --pty /bin/bash"

export PATH=$PISM_PREFIX/bin:$LOCAL/bin:$LOCAL/hdf5/bin:$LOCAL/netcdf/bin:$PATH
export PYTHONPATH=$PETSC_DIR/$PETSC_ARCH/lib:$PYTHONPATH
export PISM_MPIDO='mpirun -np'
