#!/bin/bash

umask 007

module purge
module load intel/19.1.3.304  
module load impi/2019.9.304
module load intel-mkl/2019.5.281
module load cmake/3.20.0
module load fftw/3.3.8
module load python/3.9.5
module load gsl/2.4
module load libxml2
module load curl
module load proj/6.2.0
module load udunits/2.2.28
module load zlib/1.2.11
module load libszip/2.1.1

export LOCAL_LIB_DIR=$HOME/local
export PISM_DIR=$LOCAL_LIB_DIR/pism
export PISM_PREFIX=${PISM_DIR}/bin/
export PETSC_DIR=$HOME/local/petsc
export PETSC_ARCH=arch-linux-c-opt

# start an interactive job
alias interact="srun -p debug --nodes=1 --exclusive -I --pty /bin/bash"

export PYTHONPATH=$PETSC_DIR/$PETSC_ARCH/lib:$PYTHONPATH
export LD_LIBRARY_PATH=$HOME/local/netcdf/lib:$LD_LIBRARY_PATH
export PISM_MPIDO='mpirun -np'
