#!/bin/bash

# PGI does not support C++11, so we have to use GCC
module rm PrgEnv-pgi
module load PrgEnv-gnu

# cray-mpich2 does not seem to support gcc 4.9, and neither does netcdf-hdf5parallel
module rm gcc/4.9.0
module load gcc/4.7.3

# re-load cray-mpich2 so that it picks up that we're using GCC 4.7
module rm cray-mpich2
module load cray-mpich2

# re-load cray-libsci so that it picks up that we're using GCC 4.7
module rm cray-libsci
module load cray-libsci

# prerequisite libraries
module load netcdf-hdf5parallel/4.2.0
module load fftw/3.3.0.1
module load gsl/1.15.gnu

# useful modules not needed to build PISM
module load ncview/2.1.5

# short-cut for interactive jobs
alias interact="qsub -q standard -l nodes=1:ppn=12 -I"
alias interact_gpu="qsub -q gpu -l nodes=1:ppn=16 -I"

export PISM_MPIDO='aprun -n'
