#!/bin/bash
# These commands are executed on a login or start of a PBS job.

# First, run the NAS standard setup.

if [ -e /usr/local/lib/init/global.profile ]; then
    . /usr/local/lib/init/global.profile
fi

# Add your commands here to extend your PATH, etc.

module purge
module load comp-intel/2016.2.181
module load mpi-sgi/mpt.2.15r20
module load pkgsrc/2016Q2
module load udunits/2.1.19
module load python/2.7.11
module load gcc/4.9.3

export PISM_MPIDO='mpiexec -n'
PATH=/nasa/pkgsrc/2016Q2/bin:/nasa/pkgsrc/2016Q2/sbin:$PATH
