#!/bin/bash
# These commands are executed on a login or start of a PBS job.

# First, run the NAS standard setup.

if [ -e /usr/local/lib/init/global.profile ]; then
    . /usr/local/lib/init/global.profile
fi

# Add your commands here to extend your PATH, etc.

module purge
module use -a /swbuild/analytix/tools/modulefiles
module use -a /nasa/modulefiles/testing
module load comp-intel/2020.2.254 
module load mpi-hpe/mpt.2.22 
module load szip/2.1.1 
module load hdf5/1.12.0_mpt
module load python3-intel/2020.0.014

# Increase MPI_TYPE_DEPTH from 14 to 24 (seems to be needed by HDF5
# when used with SGI MPT 2.12).
export MPI_TYPE_DEPTH=24

add_lib_path () {
    export LD_LIBRARY_PATH=$1:$LD_LIBRARY_PATH
}

add_lib_path ${LOCAL_LIB_DIR}/lib
add_lib_path ${LOCAL_LIB_DIR}/netcdf/lib

export PISM_MPIDO='mpiexec -n'
