#!/bin/bash
# These commands are executed on a login or start of a PBS job.

# First, run the NAS standard setup.

if [ -e /usr/local/lib/init/global.profile ]; then
    . /usr/local/lib/init/global.profile
fi

# Add your commands here to extend your PATH, etc.

module purge
module load comp-intel/2016.2.181
module load mpi-sgi/mpt.2.15r20
module load python/2.7.12
module load gcc/4.9.4
module load hdf5/1.8.18_mpt
module load hdf4/4.2.12
module load netcdf/4.4.1.1_mpt
module load pkgsrc/2016Q4
module load ncview/2.1.7
module use -a /nasa/modulefiles/testing
module load nco/4.6.7

add_lib_path () {
    export LD_LIBRARY_PATH=$1:$LD_LIBRARY_PATH
}

add_lib_path ${LOCAL_LIB_DIR}/lib
add_lib_path ${LOCAL_LIB_DIR}/hdf5/lib
add_lib_path ${LOCAL_LIB_DIR}/netcdf/lib

export PISM_MPIDO='mpiexec -n'
